# the file lives in `~/.config/kitty/`
# theme file resides adjacent to it

include IR_Black.conf

# match titlebar color to theme's (on GNOME)
wayland_titlebar_color background

background_opacity 0.9
font_family Cascadia Code
font_size 12

# allow running "kitty @ set-colors <file-name>"
allow_remote_control true
