# the file lives in `~/.config/kitty/`
# theme file resides adjacent to it

include catppuccin.conf

# match titlebar color to theme's (on GNOME)
wayland_titlebar_color background

background_opacity 0.95
font_family MonoLisa NF
# HiDpi Screen
font_size 18

# allow running "kitty @ set-colors <file-name>"
allow_remote_control true
