# the file lives in `~/.config/kitty/`
# the theme file resides adjacent to it
# Ayu.conf mentioned here is my customized theme

include Ayu.conf
wayland_titlebar_color background
font_size 11.5
font_family SauceCodePro Nerd Font
