# the file lives in `~/.config/kitty/`
# the theme file resides adjacent to it
# Ayu.conf mentioned here is my customized theme; find it in my kitty themes repo

include Ayu.conf
wayland_titlebar_color background
font_size 11.5
background_opacity 0.9
font_family MesloLGS NF